version: '3'
services:
  nginx:
    image: nginx:alpine
    ports: 
      - "8080:80"
    volumes:
      - ./app/var/www/dev:/var/www/dev:ro
      - ./app/volumes/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: ./app/volumes/etc/php7.4-fpm
    volumes:
      - ./app/var/www/dev:/var/www/dev:ro
    healthcheck:
     test: ["CMD", "curl", "-sS", "http://nginx | grep", "-c", "works > /dev/null"]
     interval: 5s
     timeout: 5s
     retries: 5
     test